#!/bin/bash
#
# Plugin to monitor PostgreSQL blocked queries.
#
# Author:
#   Paul A. Jungwirth <pj@illuminatedcomputing.com>
#
# Created:
#   5 October 2018
#
# Usage:
#   Place in /etc/munin/plugins/ (or link it there with ln -s)
#
# Parameters:
#   config (required)

# dbhost: The host where Postgres is running.
#         Note if you set this you will need a .pgpass file also.
dbname=${DBNAME}
dbhost=${DBHOST}
dbport=${DBPORT:-5432}
dbuser=${DBUSER}

plugin_name=`basename "$0"`
plugin_name=${plugin_name#"postgresql_blocked_queries"}
plugin_name=${plugin_name#"_"}

if [ "x$plugin_name" != "x" ]; then
  plugin_name=" - ${plugin_name}"
fi

if [ "$1" = "config" ]; then
  echo graph_args --base 1000 --lower-limit 0
  echo graph_category postgresql
  echo graph_info Shows the number of queries currently blocked
  echo graph_title PostgreSQL Blocked Queries $plugin_name
  echo graph_vlabel Queries
  echo postgresql_blocked_queries.label Queries

else
  dbfilter=''
  if [ "x$dbname" != "x" ]; then
    dbfilter="AND     (SELECT db.datname FROM pg_database db WHERE db.oid = blocked_locks.database) = '$dbfilter'"
  fi
  # This is more complex than we need,
  # but it's nice to use the whole thing
  # so you could run it by hand and get the details.
  # From https://wiki.postgresql.org/wiki/Lock_Monitoring
  q=$(cat <<EOQ
SELECT  COUNT(DISTINCT blocked_activity.pid)
FROM    pg_locks blocked_locks
JOIN    pg_stat_activity blocked_activity
ON      blocked_activity.pid = blocked_locks.pid
JOIN    pg_locks blocking_locks
ON      blocking_locks.locktype = blocked_locks.locktype
AND     NOT blocking_locks.database IS DISTINCT FROM blocked_locks.database
AND     NOT blocking_locks.relation IS DISTINCT FROM blocked_locks.relation
AND     NOT blocking_locks.page IS DISTINCT FROM blocked_locks.page
AND     NOT blocking_locks.tuple IS DISTINCT FROM blocked_locks.tuple
AND     NOT blocking_locks.virtualxid IS DISTINCT FROM blocked_locks.virtualxid
AND     NOT blocking_locks.transactionid IS DISTINCT FROM blocked_locks.transactionid
AND     NOT blocking_locks.classid IS DISTINCT FROM blocked_locks.classid
AND     NOT blocking_locks.objid IS DISTINCT FROM blocked_locks.objid
AND     NOT blocking_locks.objsubid IS DISTINCT FROM blocked_locks.objsubid
AND     blocking_locks.pid <> blocked_locks.pid
JOIN    pg_stat_activity blocking_activity
ON      blocking_activity.pid = blocking_locks.pid
WHERE   NOT blocked_locks.granted
$dbfilter
;
EOQ
)
  args="-p ${dbport}"
  if [ "x$dbuser" != "x" ]; then
    args="-U ${dbuser} ${args}"
  fi
  if [ "x$dbhost" != "x" ]; then
    args="-h ${dbhost} ${args}"
  fi
  psql ${args} -tc "$q" | while read c
  do
    test -z "${c}" && continue
    echo 'postgresql_blocked_queries.value' $c
  done
fi
